### ISSUE TITLE
Modificare la pagina "blog" eventi

### ISSUE THREAD

**Issue by CatMonster** [PowsUp/website#14]
https://www.figma.com/file/PpjAfSs5MSo9X3RCdCmsrV/Sito?type=design&node-id=54%3A23&mode=design&t=Odv5qYdmZCgzBrCx-1

**Comment by JaxzTW** [comment]
Forse è un duplicato, potrebbe essere una cosa che ho già fatto anche se non ho modificato di molto le sezioni dei blog

**Comment by JaxzTW** [comment]
#26
