### ISSUE TITLE
Creare pagina evento

### ISSUE THREAD

**Issue by CatMonster** [PowsUp/website#15]
https://www.figma.com/file/PpjAfSs5MSo9X3RCdCmsrV/Sito?type=design&node-id=54%3A21&mode=design&t=Odv5qYdmZCgzBrCx-1

**Comment by JaxzTW** [comment]
Gli stili per la hero non sembrano proprio ok, e qualsiasi modifica sembra far sempre in modo che l'immagine copra anche la navbar, need little help con tailwind

**Comment by JaxzTW** [comment]
<HeroEventoProps/>
