### ISSUE TITLE
Sistemare Navbar

### ISSUE THREAD

**Issue by JaxzTW** [PowsUp/website#19]

**Comment by CatMonster** [comment]
Che cosa ti blocca? Potresti fare una descrizione dettagliata perfavore?

**Comment by CatMonster** [comment]
ma poi scusa, in teoria questo task è duplicato, già se ne dovrebbe occupare @Daniplant con l'issue #7.
Che cosa volevi fare qua?

**Comment by JaxzTW** [comment]
Qui sto modificando il navigation.js, quello che "mi blocca" è lo stile della navigazione al centro, non sono al centro ma un pò verso destra
