### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by CatMonster** [PowsUp/website#9]
Implementare cookie consent https://github.com/orestbida/cookieconsent, prendendo spunto dalla landing page.
Fare in modo che i pixel partano solo se sono accettati.
Separare i consent singolarmente per la scelta custom

Inserire pixel:
- chat tidio, 
- google analytics

https://github.com/jop-software/astro-cookieconsent

**Comment by CatMonster** [comment]
@JaxzTW potresti fornire gli accessi di GA a @Shilvio perfavore?

**Comment by JaxzTW** [comment]
> @JaxzTW potresti fornire gli accessi di GA a @Shilvio perfavore?

Mi serve l'email, fammela mandare
